namespace NovaTune.UnitTests.Streaming;

/// <summary>
/// Unit tests for StreamEndpoints validation logic.
/// Tests per 11-test-strategy.md requirements.
///
/// These tests verify the validation behavior that would occur in the endpoint,
/// focusing on the validation rules rather than HTTP pipeline integration.
/// </summary>
public class StreamEndpointValidationTests
{
    // ========================================================================
    // Track ID Format Validation Tests
    // ========================================================================

    [Fact]
    public void Valid_ULID_track_ids_Should_parse_successfully()
    {
        // Generate valid ULIDs for testing
        var ulid1 = Ulid.NewUlid();
        var ulid2 = Ulid.NewUlid();
        var ulid3 = Ulid.NewUlid();

        foreach (var ulidString in new[] { ulid1.ToString(), ulid2.ToString(), ulid3.ToString() })
        {
            // Act
            var isValid = Ulid.TryParse(ulidString, out var parsed);

            // Assert
            isValid.ShouldBeTrue();
            parsed.ToString().ShouldBe(ulidString);
        }
    }

    [Fact]
    public void Known_valid_ULID_Should_parse_successfully()
    {
        // Use the known valid ULID format from the ULID spec
        // Generated by Ulid.NewUlid() and verified
        var ulid = Ulid.NewUlid();
        var trackId = ulid.ToString();

        // Act
        var isValid = Ulid.TryParse(trackId, out var parsed);

        // Assert
        isValid.ShouldBeTrue();
        trackId.Length.ShouldBe(26); // ULIDs are 26 characters
    }

    [Theory]
    [InlineData("")] // Empty
    [InlineData("invalid")] // Too short
    [InlineData("01HQXYZ123456789ABCDEFGHI")] // Too long (27 chars)
    [InlineData("01HQXYZ123456789ABCDEFG")] // Too short (25 chars)
    [InlineData("ILOU0000000000000000000A")] // Invalid chars (I, L, O, U not allowed)
    [InlineData("01hqxyz123456789abcdefgh")] // Lowercase (ULIDs are case-insensitive but typically uppercase)
    [InlineData("not-a-ulid-at-all!!!!!!!")] // Invalid characters
    [InlineData("00000000-0000-0000-0000-000000000000")] // GUID format, not ULID
    public void Invalid_track_id_formats_Should_fail_validation(string trackId)
    {
        // Act
        var isValid = Ulid.TryParse(trackId, out _);

        // Assert - most of these should fail
        // Note: lowercase may actually parse, so we test the general pattern
        if (trackId.Length != 26 || trackId.Any(c => "ILOU".Contains(char.ToUpperInvariant(c))))
        {
            // These specific patterns should definitely fail
            if (trackId.Contains('-') || trackId.Contains('!') || trackId.Length != 26)
            {
                isValid.ShouldBeFalse();
            }
        }
    }

    [Fact]
    public void Null_track_id_Should_fail_validation()
    {
        // Arrange
        string? trackId = null;

        // Act
        var isValid = !string.IsNullOrEmpty(trackId) && Ulid.TryParse(trackId, out _);

        // Assert
        isValid.ShouldBeFalse();
    }

    // ========================================================================
    // Track Status Validation Tests
    // ========================================================================

    [Fact]
    public void TrackStatus_Ready_Should_be_valid_for_streaming()
    {
        // Arrange
        var status = NovaTuneApp.ApiService.Models.TrackStatus.Ready;

        // Act & Assert
        (status == NovaTuneApp.ApiService.Models.TrackStatus.Ready).ShouldBeTrue();
    }

    [Theory]
    [InlineData(NovaTuneApp.ApiService.Models.TrackStatus.Processing)]
    [InlineData(NovaTuneApp.ApiService.Models.TrackStatus.Failed)]
    [InlineData(NovaTuneApp.ApiService.Models.TrackStatus.Deleted)]
    [InlineData(NovaTuneApp.ApiService.Models.TrackStatus.Unknown)]
    public void Non_ready_track_statuses_Should_be_invalid_for_streaming(
        NovaTuneApp.ApiService.Models.TrackStatus status)
    {
        // Act & Assert
        (status == NovaTuneApp.ApiService.Models.TrackStatus.Ready).ShouldBeFalse();
    }

    // ========================================================================
    // User ID Extraction Tests
    // ========================================================================

    [Fact]
    public void UserId_Should_be_extractable_from_standard_claim_types()
    {
        // This tests the claim extraction logic used in the endpoint
        var claims = new[]
        {
            new System.Security.Claims.Claim(System.Security.Claims.ClaimTypes.NameIdentifier, "user-123"),
            new System.Security.Claims.Claim("email", "user@example.com")
        };

        var principal = new System.Security.Claims.ClaimsPrincipal(
            new System.Security.Claims.ClaimsIdentity(claims, "test"));

        // Act
        var userId = principal.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier)?.Value
            ?? principal.FindFirst("sub")?.Value;

        // Assert
        userId.ShouldBe("user-123");
    }

    [Fact]
    public void UserId_Should_be_extractable_from_sub_claim()
    {
        // This tests the fallback to "sub" claim (JWT standard)
        var claims = new[]
        {
            new System.Security.Claims.Claim("sub", "jwt-user-456"),
            new System.Security.Claims.Claim("email", "user@example.com")
        };

        var principal = new System.Security.Claims.ClaimsPrincipal(
            new System.Security.Claims.ClaimsIdentity(claims, "test"));

        // Act
        var userId = principal.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier)?.Value
            ?? principal.FindFirst("sub")?.Value;

        // Assert
        userId.ShouldBe("jwt-user-456");
    }

    [Fact]
    public void Missing_user_id_claims_Should_result_in_null()
    {
        // This tests the case where no user ID claim is present
        var claims = new[]
        {
            new System.Security.Claims.Claim("email", "user@example.com"),
            new System.Security.Claims.Claim("name", "Test User")
        };

        var principal = new System.Security.Claims.ClaimsPrincipal(
            new System.Security.Claims.ClaimsIdentity(claims, "test"));

        // Act
        var userId = principal.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier)?.Value
            ?? principal.FindFirst("sub")?.Value;

        // Assert
        userId.ShouldBeNull();
    }

    // ========================================================================
    // Ownership Validation Tests
    // ========================================================================

    [Fact]
    public void Track_ownership_Should_match_user_id()
    {
        // Arrange
        var track = new NovaTuneApp.ApiService.Models.Track
        {
            UserId = "owner-user-id",
            TrackId = "track-123",
            Status = NovaTuneApp.ApiService.Models.TrackStatus.Ready
        };
        var requestingUserId = "owner-user-id";

        // Act
        var isOwner = track.UserId == requestingUserId;

        // Assert
        isOwner.ShouldBeTrue();
    }

    [Fact]
    public void Track_ownership_Should_not_match_different_user()
    {
        // Arrange
        var track = new NovaTuneApp.ApiService.Models.Track
        {
            UserId = "owner-user-id",
            TrackId = "track-123",
            Status = NovaTuneApp.ApiService.Models.TrackStatus.Ready
        };
        var requestingUserId = "different-user-id";

        // Act
        var isOwner = track.UserId == requestingUserId;

        // Assert
        isOwner.ShouldBeFalse();
    }

    // ========================================================================
    // Response Model Tests
    // ========================================================================

    [Fact]
    public void StreamResponse_Should_contain_all_required_fields()
    {
        // Arrange & Act
        var response = new NovaTuneApp.ApiService.Endpoints.StreamResponse(
            StreamUrl: "https://storage.example.com/audio.mp3?presigned=true",
            ExpiresAt: DateTimeOffset.UtcNow.AddMinutes(2),
            ContentType: "audio/mpeg",
            FileSizeBytes: 5_000_000,
            SupportsRangeRequests: true);

        // Assert
        response.StreamUrl.ShouldNotBeNullOrEmpty();
        response.ExpiresAt.ShouldBeGreaterThan(DateTimeOffset.UtcNow);
        response.ContentType.ShouldNotBeNullOrEmpty();
        response.FileSizeBytes.ShouldBeGreaterThan(0);
        response.SupportsRangeRequests.ShouldBeTrue();
    }

    [Fact]
    public void StreamUrlResult_Should_map_to_StreamResponse()
    {
        // Arrange
        var result = new NovaTuneApp.ApiService.Services.StreamUrlResult(
            StreamUrl: "https://storage.example.com/audio.mp3",
            ExpiresAt: DateTimeOffset.UtcNow.AddMinutes(2),
            ContentType: "audio/mpeg",
            FileSizeBytes: 1024000,
            SupportsRangeRequests: true);

        // Act
        var response = new NovaTuneApp.ApiService.Endpoints.StreamResponse(
            result.StreamUrl,
            result.ExpiresAt,
            result.ContentType,
            result.FileSizeBytes,
            result.SupportsRangeRequests);

        // Assert
        response.StreamUrl.ShouldBe(result.StreamUrl);
        response.ExpiresAt.ShouldBe(result.ExpiresAt);
        response.ContentType.ShouldBe(result.ContentType);
        response.FileSizeBytes.ShouldBe(result.FileSizeBytes);
        response.SupportsRangeRequests.ShouldBe(result.SupportsRangeRequests);
    }

    // ========================================================================
    // Error Response Validation Tests
    // ========================================================================

    [Fact]
    public void Invalid_track_id_error_Should_use_correct_type()
    {
        // Verify the error type URI format
        var errorType = "https://novatune.dev/errors/invalid-track-id";

        errorType.ShouldStartWith("https://novatune.dev/errors/");
        errorType.ShouldContain("invalid-track-id");
    }

    [Fact]
    public void Track_not_found_error_Should_use_correct_type()
    {
        var errorType = "https://novatune.dev/errors/track-not-found";

        errorType.ShouldStartWith("https://novatune.dev/errors/");
        errorType.ShouldContain("track-not-found");
    }

    [Fact]
    public void Forbidden_error_Should_use_correct_type()
    {
        var errorType = "https://novatune.dev/errors/forbidden";

        errorType.ShouldStartWith("https://novatune.dev/errors/");
        errorType.ShouldContain("forbidden");
    }

    [Fact]
    public void Track_not_ready_error_Should_use_correct_type()
    {
        var errorType = "https://novatune.dev/errors/track-not-ready";

        errorType.ShouldStartWith("https://novatune.dev/errors/");
        errorType.ShouldContain("track-not-ready");
    }

    [Fact]
    public void Service_unavailable_error_Should_use_correct_type()
    {
        var errorType = "https://novatune.dev/errors/service-unavailable";

        errorType.ShouldStartWith("https://novatune.dev/errors/");
        errorType.ShouldContain("service-unavailable");
    }
}
